import { StyleSheet } from 'react-native';
import { colors } from '@/constants/colors';
import { typography } from '@/constants/typography';
import { spacing, radius } from '@/constants/spacing';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.dark.bg.primary,
  },
  customHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.base,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.dark.border.subtle,
    backgroundColor: colors.dark.bg.primary,
  },
  headerBackButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  headerTitle: {
    fontSize: typography.fontSize.lg,
    fontWeight: 'bold',
    color: colors.dark.text.primary,
  },
  headerRight: {
    width: 40,
  },
  scrollContent: {
    padding: spacing.base,
  },
  exerciseSection: {
    gap: spacing.md,
    marginBottom: spacing.xl,
    width: '100%',
  },
  swipeableContainer: {
    overflow: 'visible',
  },
  deleteSwipeButton: {
    backgroundColor: colors.dark.accent.primary,
    justifyContent: 'center',
    alignItems: 'center',
    width: 70,
    borderTopRightRadius: radius.md,
    borderBottomRightRadius: radius.md,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
    height: '100%',
  },
  deleteSwipeText: {
    color: colors.white,
    fontSize: 10,
    fontWeight: 'bold',
    marginTop: 4,
  },
  activeItem: {
    opacity: 0.8,
  },
  exerciseSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  exerciseSectionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    flex: 1,
    minWidth: 0,
  },
  exerciseIconWrapper: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: colors.dark.accent.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
  },
  exerciseName: {
    color: colors.dark.text.primary,
    fontSize: typography.fontSize.md,
    fontWeight: 'bold',
    textTransform: 'capitalize',
    flexShrink: 1,
  },
  headerCheckCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  exerciseCard: {
    padding: 0,
    borderWidth: 1,
    borderColor: colors.dark.border.subtle,
    overflow: 'hidden',
  },
  tableHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.ss,
    backgroundColor: colors.dark.bg.elevated,
    borderBottomWidth: 1,
    borderBottomColor: colors.dark.border.subtle,
  },
  tableHeaderSet: {
    width: 40,
    color: colors.dark.text.secondary,
    textAlign: 'center',
  },
  tableHeaderMain: {
    flex: 1,
    color: colors.dark.text.secondary,
    textAlign: 'center',
  },
  tableHeaderCheck: {
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  setRow: {
    flexDirection: 'row',
    padding: spacing.sm,
    alignItems: 'center',
  },
  setNumber: {
    width: 40,
    color: colors.dark.text.primary,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  setInputContainer: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: spacing.xs,
  },
  inlineInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.dark.bg.tertiary,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: 'transparent',
    overflow: 'hidden',
    height: 36,
    width: '100%',
  },
  inlineInputWrapperFocused: {
    borderColor: colors.dark.accent.primary,
    backgroundColor: colors.dark.bg.secondary,
  },
  inlineInputWrapperCompleted: {
    backgroundColor: 'transparent',
  },
  textInput: {
    flex: 1,
    color: colors.dark.text.primary,
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
    fontWeight: 'bold',
    padding: 0,
  },
  setCheckContainer: {
    width: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  addSetButton: {
    padding: spacing.md,
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: colors.dark.border.subtle,
    backgroundColor: colors.dark.bg.secondary,
  },
  addSetContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  addSetText: {
    color: colors.dark.accent.primary,
    fontWeight: 'bold',
  },
  globalAddExerciseBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.dark.border.default,
    backgroundColor: colors.dark.bg.tertiary,
    marginTop: spacing.sm,
  },
  globalAddExerciseText: {
    color: colors.dark.text.primary,
    fontWeight: 'bold',
    fontSize: typography.fontSize.base,
  },
  selectionContainer: {
    flex: 1,
    padding: spacing.base,
    backgroundColor: colors.dark.bg.primary,
  },
  selectionTitle: {
    fontSize: typography.fontSize.lg,
    fontWeight: 'bold',
    color: colors.dark.text.primary,
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.xs,
  },
  muscleGroupsSection: {
    paddingHorizontal: spacing.md,
    marginBottom: spacing.sm,
  },
  muscleGroupGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'flex-start',
  },
  muscleGroupItemWrapper: {
    // width is set dynamically inline
  },
  muscleGroupItem: {
    width: '100%',
    height: 48,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    paddingHorizontal: spacing.xs,
  },
  muscleGroupText: {
    fontSize: typography.fontSize.sm,
    fontWeight: 'bold',
    textAlign: 'center',
    textAlignVertical: 'center',
    includeFontPadding: false,
  },
  deleteBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.dark.accent.danger,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    borderWidth: 1.5,
    borderColor: colors.dark.bg.primary,
  },
  exercisesHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.xs,
  },
  exercisesListTitle: {
    fontSize: typography.fontSize.md,
    fontWeight: 'bold',
    color: colors.dark.text.primary,
  },
  selectListContent: {
    paddingBottom: spacing.base,
    gap: spacing.sm,
  },
  exerciseSelectItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.md,
    backgroundColor: colors.dark.bg.secondary,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.dark.border.subtle,
  },
  exerciseSelectItemChecked: {
    borderColor: colors.dark.accent.primary,
    backgroundColor: 'rgba(210, 74, 66, 0.08)',
  },
  exerciseSelectName: {
    fontSize: typography.fontSize.base,
    fontWeight: 'bold',
    color: colors.dark.text.primary,
  },
  checkboxCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.dark.border.default,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxCircleChecked: {
    backgroundColor: colors.dark.accent.primary,
    borderColor: colors.dark.accent.primary,
  },
  emptyExercisesContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: spacing.xxl,
  },
  emptyExercisesText: {
    color: colors.dark.text.secondary,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
  },
  submitButtonContainer: {
    padding: spacing.base,
    paddingBottom: spacing.xl,
    backgroundColor: colors.dark.bg.primary,
    borderTopWidth: 1,
    borderTopColor: colors.dark.border.subtle,
  },
  cancelEditBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xs,
  },
  cancelEditText: {
    color: colors.dark.text.secondary,
    fontSize: typography.fontSize.base,
    fontWeight: '600',
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  toastContainer: {
    position: 'absolute',
    bottom: 130,
    left: spacing.base,
    right: spacing.base,
    backgroundColor: colors.dark.bg.elevated,
    borderWidth: 1,
    borderColor: colors.dark.accent.warning,
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.md,
    borderRadius: radius.md,
    gap: spacing.sm,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 9999,
  },
  toastText: {
    color: colors.dark.text.primary,
    fontSize: typography.fontSize.sm,
    fontWeight: '600',
    flex: 1,
  },
  floatingBubble: {
    position: 'absolute',
    bottom: 180,
    right: spacing.base,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.dark.accent.primary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    zIndex: 100,
  },
  thumbnailContainer: {
    width: 44,
    height: 44,
    borderRadius: radius.sm,
    backgroundColor: colors.dark.bg.tertiary,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  thumbnail: {
    width: '100%',
    height: '100%',
  },
});
